name: exattraffic
description: EXAT Traffic

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.0.4+32

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^1.1.0
  intl: ^0.16.1
  google_maps_flutter: ^0.5.26+4
  geolocator: ^5.3.1
  provider: ^4.1.2
  uuid: ^2.0.4
  http: ^0.12.1
  lazy_indexed_stack: ^0.0.1
  flutter_bloc: ^5.0.1
  equatable: ^1.0.0
  rxdart: ^0.23.1
  webview_flutter: ^0.3.22+1
  connectivity: ^0.4.9
  #video_player: ^0.10.11+2
  flutter_vlc_player: ^3.0.3
  rflutter_alert: ^1.0.3
  store_redirect: ^1.0.2
  carousel_slider: ^2.2.1
  firebase_messaging: ^6.0.16
  flutter_cache_manager: ^1.4.1
  pull_to_refresh: ^1.6.0
  cached_network_image: ^2.2.0+1
  package_info: ^0.4.1

  # Map markers clustering
  fluster: ^1.1.2

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    - assets/images/
    - assets/images/login/
    - assets/images/home/
    - assets/images/favorite/
    - assets/images/incident/
    - assets/images/nav_bar/
    - assets/images/drawer/
    - assets/images/map_tools/
    - assets/images/cctv_details/
    - assets/images/rest_area_details/
    - assets/images/police_station_details/
    - assets/images/toll_plaza_details/
    - assets/images/layers/
    - assets/images/map_markers/
    - assets/images/route/
    - assets/images/schematic_maps/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: DBHeavent
      fonts:
        - asset: assets/fonts/DBHeavent.ttf
    - family: DBHeavent-Bold
      fonts:
        - asset: assets/fonts/DBHeavent-Bold.ttf
    - family: DBHeavent-Med
      fonts:
        - asset: assets/fonts/DBHeavent-Med.ttf
    - family: DBHeavent-Light
      fonts:
        - asset: assets/fonts/DBHeaventt-Light.ttf
